### ISSUE TITLE
Google has rate limited this IP

### ISSUE THREAD

**Issue by ghost** [EdmundMartin/search_it#4]
Any tips on how I would integrate proxied requests or add VPN functionality to the existing script to solve the issue ?

**Comment by EdmundMartin** [comment]
There is already support for proxies. A proxy as a string can be passed into the scrape request object and will then be used to scrape.
`
request = ScrapeRequest("watch movies online", 30, proxy="https://126.91.12.1:8000")
`

Additionally, you might to want to increase the sleep between paginating results pages as this will decrease the amount of blocks you will receive.

**Comment by ghost** [comment]
Alright, your library's working great ! Thanks and ping me if I can be any help at all to this project !
